// Code generated by MockGen. DO NOT EDIT.
// Source: my_project/internal/users/usecase (interfaces: UserUsecase)
//
// Generated by this command:
//
//	mockgen -destination=../test/mock_user_usecase.go -package=test my_project/internal/users/usecase UserUsecase
//

// Package test is a generated GoMock package.
package test

import (
	context "context"
	multipart "mime/multipart"
	usecase "my_project/internal/users/usecase"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserUsecase is a mock of UserUsecase interface.
type MockUserUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUserUsecaseMockRecorder
	isgomock struct{}
}

// MockUserUsecaseMockRecorder is the mock recorder for MockUserUsecase.
type MockUserUsecaseMockRecorder struct {
	mock *MockUserUsecase
}

// NewMockUserUsecase creates a new mock instance.
func NewMockUserUsecase(ctrl *gomock.Controller) *MockUserUsecase {
	mock := &MockUserUsecase{ctrl: ctrl}
	mock.recorder = &MockUserUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserUsecase) EXPECT() *MockUserUsecaseMockRecorder {
	return m.recorder
}

// ChangePassword mocks base method.
func (m *MockUserUsecase) ChangePassword(ctx context.Context, userID string, req usecase.ChangePasswordRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePassword", ctx, userID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockUserUsecaseMockRecorder) ChangePassword(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockUserUsecase)(nil).ChangePassword), ctx, userID, req)
}

// DeleteUser mocks base method.
func (m *MockUserUsecase) DeleteUser(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUserUsecaseMockRecorder) DeleteUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUserUsecase)(nil).DeleteUser), ctx, userID)
}

// DisableTwoFactor mocks base method.
func (m *MockUserUsecase) DisableTwoFactor(ctx context.Context, userID string, req usecase.DisableTwoFactorRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableTwoFactor", ctx, userID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableTwoFactor indicates an expected call of DisableTwoFactor.
func (mr *MockUserUsecaseMockRecorder) DisableTwoFactor(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableTwoFactor", reflect.TypeOf((*MockUserUsecase)(nil).DisableTwoFactor), ctx, userID, req)
}

// EnableTwoFactor mocks base method.
func (m *MockUserUsecase) EnableTwoFactor(ctx context.Context, userID string, req usecase.EnableTwoFactorRequest) (usecase.EnableTwoFactorResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableTwoFactor", ctx, userID, req)
	ret0, _ := ret[0].(usecase.EnableTwoFactorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnableTwoFactor indicates an expected call of EnableTwoFactor.
func (mr *MockUserUsecaseMockRecorder) EnableTwoFactor(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableTwoFactor", reflect.TypeOf((*MockUserUsecase)(nil).EnableTwoFactor), ctx, userID, req)
}

// GetUserProfile mocks base method.
func (m *MockUserUsecase) GetUserProfile(ctx context.Context, userID string) (usecase.UserProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserProfile", ctx, userID)
	ret0, _ := ret[0].(usecase.UserProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserProfile indicates an expected call of GetUserProfile.
func (mr *MockUserUsecaseMockRecorder) GetUserProfile(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserProfile", reflect.TypeOf((*MockUserUsecase)(nil).GetUserProfile), ctx, userID)
}

// SetupTwoFactor mocks base method.
func (m *MockUserUsecase) SetupTwoFactor(ctx context.Context, userID string) (usecase.TwoFactorSetupResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupTwoFactor", ctx, userID)
	ret0, _ := ret[0].(usecase.TwoFactorSetupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetupTwoFactor indicates an expected call of SetupTwoFactor.
func (mr *MockUserUsecaseMockRecorder) SetupTwoFactor(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupTwoFactor", reflect.TypeOf((*MockUserUsecase)(nil).SetupTwoFactor), ctx, userID)
}

// UpdateUserProfile mocks base method.
func (m *MockUserUsecase) UpdateUserProfile(ctx context.Context, userID string, req usecase.UpdateUserRequest) (usecase.UserProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserProfile", ctx, userID, req)
	ret0, _ := ret[0].(usecase.UserProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserProfile indicates an expected call of UpdateUserProfile.
func (mr *MockUserUsecaseMockRecorder) UpdateUserProfile(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserProfile", reflect.TypeOf((*MockUserUsecase)(nil).UpdateUserProfile), ctx, userID, req)
}

// UploadAvatar mocks base method.
func (m *MockUserUsecase) UploadAvatar(ctx context.Context, userID string, fileHeader *multipart.FileHeader) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadAvatar", ctx, userID, fileHeader)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadAvatar indicates an expected call of UploadAvatar.
func (mr *MockUserUsecaseMockRecorder) UploadAvatar(ctx, userID, fileHeader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadAvatar", reflect.TypeOf((*MockUserUsecase)(nil).UploadAvatar), ctx, userID, fileHeader)
}
