// Code generated by MockGen. DO NOT EDIT.
// Source: my_project/internal/auth/repository (interfaces: UserRepository)
//
// Generated by this command:
//
//	mockgen -destination=../test/mock_user_repository.go -package=test my_project/internal/auth/repository UserRepository
//

// Package test is a generated GoMock package.
package test

import (
	context "context"
	domain "my_project/internal/auth/domain"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// CreateSession mocks base method.
func (m *MockUserRepository) CreateSession(ctx context.Context, session *domain.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockUserRepositoryMockRecorder) CreateSession(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockUserRepository)(nil).CreateSession), ctx, session)
}

// CreateUser mocks base method.
func (m *MockUserRepository) CreateUser(ctx context.Context, user *domain.UserAuth) (*domain.UserAuth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(*domain.UserAuth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserRepositoryMockRecorder) CreateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserRepository)(nil).CreateUser), ctx, user)
}

// CreateUserTwoFactor mocks base method.
func (m *MockUserRepository) CreateUserTwoFactor(ctx context.Context, twoFactor *domain.UserTwoFactor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserTwoFactor", ctx, twoFactor)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUserTwoFactor indicates an expected call of CreateUserTwoFactor.
func (mr *MockUserRepositoryMockRecorder) CreateUserTwoFactor(ctx, twoFactor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserTwoFactor", reflect.TypeOf((*MockUserRepository)(nil).CreateUserTwoFactor), ctx, twoFactor)
}

// DeleteAllSessionsByUserID mocks base method.
func (m *MockUserRepository) DeleteAllSessionsByUserID(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllSessionsByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllSessionsByUserID indicates an expected call of DeleteAllSessionsByUserID.
func (mr *MockUserRepositoryMockRecorder) DeleteAllSessionsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllSessionsByUserID", reflect.TypeOf((*MockUserRepository)(nil).DeleteAllSessionsByUserID), ctx, userID)
}

// DeleteExpiredSessions mocks base method.
func (m *MockUserRepository) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredSessions", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpiredSessions indicates an expected call of DeleteExpiredSessions.
func (mr *MockUserRepositoryMockRecorder) DeleteExpiredSessions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredSessions", reflect.TypeOf((*MockUserRepository)(nil).DeleteExpiredSessions), ctx)
}

// DeleteSessionByToken mocks base method.
func (m *MockUserRepository) DeleteSessionByToken(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSessionByToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSessionByToken indicates an expected call of DeleteSessionByToken.
func (mr *MockUserRepositoryMockRecorder) DeleteSessionByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSessionByToken", reflect.TypeOf((*MockUserRepository)(nil).DeleteSessionByToken), ctx, token)
}

// DeleteUserTwoFactor mocks base method.
func (m *MockUserRepository) DeleteUserTwoFactor(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserTwoFactor", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserTwoFactor indicates an expected call of DeleteUserTwoFactor.
func (mr *MockUserRepositoryMockRecorder) DeleteUserTwoFactor(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserTwoFactor", reflect.TypeOf((*MockUserRepository)(nil).DeleteUserTwoFactor), ctx, userID)
}

// GetSessionByToken mocks base method.
func (m *MockUserRepository) GetSessionByToken(ctx context.Context, token string) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByToken", ctx, token)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByToken indicates an expected call of GetSessionByToken.
func (mr *MockUserRepositoryMockRecorder) GetSessionByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByToken", reflect.TypeOf((*MockUserRepository)(nil).GetSessionByToken), ctx, token)
}

// GetUserByEmail mocks base method.
func (m *MockUserRepository) GetUserByEmail(ctx context.Context, email string) (*domain.UserAuth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*domain.UserAuth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockUserRepositoryMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockUserRepository)(nil).GetUserByEmail), ctx, email)
}

// GetUserByGoogleID mocks base method.
func (m *MockUserRepository) GetUserByGoogleID(ctx context.Context, googleID string) (*domain.UserAuth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByGoogleID", ctx, googleID)
	ret0, _ := ret[0].(*domain.UserAuth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByGoogleID indicates an expected call of GetUserByGoogleID.
func (mr *MockUserRepositoryMockRecorder) GetUserByGoogleID(ctx, googleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByGoogleID", reflect.TypeOf((*MockUserRepository)(nil).GetUserByGoogleID), ctx, googleID)
}

// GetUserByID mocks base method.
func (m *MockUserRepository) GetUserByID(ctx context.Context, userID uuid.UUID) (*domain.UserAuth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(*domain.UserAuth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserRepositoryMockRecorder) GetUserByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserRepository)(nil).GetUserByID), ctx, userID)
}

// GetUserByResetToken mocks base method.
func (m *MockUserRepository) GetUserByResetToken(ctx context.Context, token string) (*domain.UserAuth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByResetToken", ctx, token)
	ret0, _ := ret[0].(*domain.UserAuth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByResetToken indicates an expected call of GetUserByResetToken.
func (mr *MockUserRepositoryMockRecorder) GetUserByResetToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByResetToken", reflect.TypeOf((*MockUserRepository)(nil).GetUserByResetToken), ctx, token)
}

// GetUserTwoFactor mocks base method.
func (m *MockUserRepository) GetUserTwoFactor(ctx context.Context, userID uuid.UUID) (*domain.UserTwoFactor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserTwoFactor", ctx, userID)
	ret0, _ := ret[0].(*domain.UserTwoFactor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserTwoFactor indicates an expected call of GetUserTwoFactor.
func (mr *MockUserRepositoryMockRecorder) GetUserTwoFactor(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserTwoFactor", reflect.TypeOf((*MockUserRepository)(nil).GetUserTwoFactor), ctx, userID)
}

// ResetPassword mocks base method.
func (m *MockUserRepository) ResetPassword(ctx context.Context, userID uuid.UUID, newPasswordHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetPassword", ctx, userID, newPasswordHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetPassword indicates an expected call of ResetPassword.
func (mr *MockUserRepositoryMockRecorder) ResetPassword(ctx, userID, newPasswordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetPassword", reflect.TypeOf((*MockUserRepository)(nil).ResetPassword), ctx, userID, newPasswordHash)
}

// SetResetPasswordToken mocks base method.
func (m *MockUserRepository) SetResetPasswordToken(ctx context.Context, email, token string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetResetPasswordToken", ctx, email, token, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetResetPasswordToken indicates an expected call of SetResetPasswordToken.
func (mr *MockUserRepositoryMockRecorder) SetResetPasswordToken(ctx, email, token, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetResetPasswordToken", reflect.TypeOf((*MockUserRepository)(nil).SetResetPasswordToken), ctx, email, token, expiresAt)
}

// UpdateGoogleOAuth mocks base method.
func (m *MockUserRepository) UpdateGoogleOAuth(ctx context.Context, userID uuid.UUID, googleID string, provider domain.OAuthProvider) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGoogleOAuth", ctx, userID, googleID, provider)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGoogleOAuth indicates an expected call of UpdateGoogleOAuth.
func (mr *MockUserRepositoryMockRecorder) UpdateGoogleOAuth(ctx, userID, googleID, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGoogleOAuth", reflect.TypeOf((*MockUserRepository)(nil).UpdateGoogleOAuth), ctx, userID, googleID, provider)
}

// UpdateLastLoginAt mocks base method.
func (m *MockUserRepository) UpdateLastLoginAt(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastLoginAt", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastLoginAt indicates an expected call of UpdateLastLoginAt.
func (mr *MockUserRepositoryMockRecorder) UpdateLastLoginAt(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastLoginAt", reflect.TypeOf((*MockUserRepository)(nil).UpdateLastLoginAt), ctx, userID)
}

// UpdateUserTwoFactor mocks base method.
func (m *MockUserRepository) UpdateUserTwoFactor(ctx context.Context, twoFactor *domain.UserTwoFactor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserTwoFactor", ctx, twoFactor)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserTwoFactor indicates an expected call of UpdateUserTwoFactor.
func (mr *MockUserRepositoryMockRecorder) UpdateUserTwoFactor(ctx, twoFactor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserTwoFactor", reflect.TypeOf((*MockUserRepository)(nil).UpdateUserTwoFactor), ctx, twoFactor)
}

// UserExistsByEmail mocks base method.
func (m *MockUserRepository) UserExistsByEmail(ctx context.Context, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserExistsByEmail", ctx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserExistsByEmail indicates an expected call of UserExistsByEmail.
func (mr *MockUserRepositoryMockRecorder) UserExistsByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserExistsByEmail", reflect.TypeOf((*MockUserRepository)(nil).UserExistsByEmail), ctx, email)
}
