// Code generated by MockGen. DO NOT EDIT.
// Source: my_project/internal/payment/client (interfaces: Provider)
//
// Generated by this command:
//
//	mockgen -destination=../test/mock_provider.go -package=test my_project/internal/payment/client Provider
//

// Package test is a generated GoMock package.
package test

import (
	reflect "reflect"

	stripe "github.com/stripe/stripe-go/v84"
	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// ConstructEvent mocks base method.
func (m *MockProvider) ConstructEvent(body []byte, signature string) (stripe.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConstructEvent", body, signature)
	ret0, _ := ret[0].(stripe.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConstructEvent indicates an expected call of ConstructEvent.
func (mr *MockProviderMockRecorder) ConstructEvent(body, signature any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConstructEvent", reflect.TypeOf((*MockProvider)(nil).ConstructEvent), body, signature)
}

// CreateCheckoutSession mocks base method.
func (m *MockProvider) CreateCheckoutSession(email, priceID, userID, plan string, quantity int) (*stripe.CheckoutSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCheckoutSession", email, priceID, userID, plan, quantity)
	ret0, _ := ret[0].(*stripe.CheckoutSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCheckoutSession indicates an expected call of CreateCheckoutSession.
func (mr *MockProviderMockRecorder) CreateCheckoutSession(email, priceID, userID, plan, quantity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCheckoutSession", reflect.TypeOf((*MockProvider)(nil).CreateCheckoutSession), email, priceID, userID, plan, quantity)
}

// CreatePortalSession mocks base method.
func (m *MockProvider) CreatePortalSession(customerID string) (*stripe.BillingPortalSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePortalSession", customerID)
	ret0, _ := ret[0].(*stripe.BillingPortalSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePortalSession indicates an expected call of CreatePortalSession.
func (mr *MockProviderMockRecorder) CreatePortalSession(customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePortalSession", reflect.TypeOf((*MockProvider)(nil).CreatePortalSession), customerID)
}
