// Code generated by MockGen. DO NOT EDIT.
// Source: my_project/internal/payment/usecase (interfaces: PaymentUsecase)
//
// Generated by this command:
//
//	mockgen -destination=../test/mock_usecase.go -package=test my_project/internal/payment/usecase PaymentUsecase
//

// Package test is a generated GoMock package.
package test

import (
	context "context"
	http "net/http"
	reflect "reflect"
	usecase "my_project/internal/payment/usecase"

	gomock "go.uber.org/mock/gomock"
)

// MockPaymentUsecase is a mock of PaymentUsecase interface.
type MockPaymentUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentUsecaseMockRecorder
	isgomock struct{}
}

// MockPaymentUsecaseMockRecorder is the mock recorder for MockPaymentUsecase.
type MockPaymentUsecaseMockRecorder struct {
	mock *MockPaymentUsecase
}

// NewMockPaymentUsecase creates a new mock instance.
func NewMockPaymentUsecase(ctrl *gomock.Controller) *MockPaymentUsecase {
	mock := &MockPaymentUsecase{ctrl: ctrl}
	mock.recorder = &MockPaymentUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentUsecase) EXPECT() *MockPaymentUsecaseMockRecorder {
	return m.recorder
}

// CreateCheckoutSession mocks base method.
func (m *MockPaymentUsecase) CreateCheckoutSession(ctx context.Context, id, email string, input usecase.CreateCheckoutSessionInput) (usecase.CreateCheckoutSessionOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCheckoutSession", ctx, id, email, input)
	ret0, _ := ret[0].(usecase.CreateCheckoutSessionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCheckoutSession indicates an expected call of CreateCheckoutSession.
func (mr *MockPaymentUsecaseMockRecorder) CreateCheckoutSession(ctx, id, email, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCheckoutSession", reflect.TypeOf((*MockPaymentUsecase)(nil).CreateCheckoutSession), ctx, id, email, input)
}

// CreatePortalSession mocks base method.
func (m *MockPaymentUsecase) CreatePortalSession(ctx context.Context, userID string) (usecase.CreatePortalSessionOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePortalSession", ctx, userID)
	ret0, _ := ret[0].(usecase.CreatePortalSessionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePortalSession indicates an expected call of CreatePortalSession.
func (mr *MockPaymentUsecaseMockRecorder) CreatePortalSession(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePortalSession", reflect.TypeOf((*MockPaymentUsecase)(nil).CreatePortalSession), ctx, userID)
}

// HandleWebhook mocks base method.
func (m *MockPaymentUsecase) HandleWebhook(r *http.Request) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleWebhook", r)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleWebhook indicates an expected call of HandleWebhook.
func (mr *MockPaymentUsecaseMockRecorder) HandleWebhook(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleWebhook", reflect.TypeOf((*MockPaymentUsecase)(nil).HandleWebhook), r)
}