// Code generated by MockGen. DO NOT EDIT.
// Source: my_project/internal/payment/repository (interfaces: SubscriptionRepository)
//
// Generated by this command:
//
//	mockgen -destination=../test/mock_subscription_repository.go -package=test my_project/internal/payment/repository SubscriptionRepository
//

// Package test is a generated GoMock package.
package test

import (
	context "context"
	domain "my_project/internal/payment/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSubscriptionRepository is a mock of SubscriptionRepository interface.
type MockSubscriptionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionRepositoryMockRecorder
	isgomock struct{}
}

// MockSubscriptionRepositoryMockRecorder is the mock recorder for MockSubscriptionRepository.
type MockSubscriptionRepositoryMockRecorder struct {
	mock *MockSubscriptionRepository
}

// NewMockSubscriptionRepository creates a new mock instance.
func NewMockSubscriptionRepository(ctrl *gomock.Controller) *MockSubscriptionRepository {
	mock := &MockSubscriptionRepository{ctrl: ctrl}
	mock.recorder = &MockSubscriptionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionRepository) EXPECT() *MockSubscriptionRepositoryMockRecorder {
	return m.recorder
}

// CreateSubscription mocks base method.
func (m *MockSubscriptionRepository) CreateSubscription(ctx context.Context, subscription *domain.Subscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubscription", ctx, subscription)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSubscription indicates an expected call of CreateSubscription.
func (mr *MockSubscriptionRepositoryMockRecorder) CreateSubscription(ctx, subscription any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubscription", reflect.TypeOf((*MockSubscriptionRepository)(nil).CreateSubscription), ctx, subscription)
}

// GetSubscriptionByCustomerID mocks base method.
func (m *MockSubscriptionRepository) GetSubscriptionByCustomerID(ctx context.Context, customerID string) (*domain.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionByCustomerID", ctx, customerID)
	ret0, _ := ret[0].(*domain.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionByCustomerID indicates an expected call of GetSubscriptionByCustomerID.
func (mr *MockSubscriptionRepositoryMockRecorder) GetSubscriptionByCustomerID(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionByCustomerID", reflect.TypeOf((*MockSubscriptionRepository)(nil).GetSubscriptionByCustomerID), ctx, customerID)
}

// GetSubscriptionBySubID mocks base method.
func (m *MockSubscriptionRepository) GetSubscriptionBySubID(ctx context.Context, subID string) (*domain.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionBySubID", ctx, subID)
	ret0, _ := ret[0].(*domain.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionBySubID indicates an expected call of GetSubscriptionBySubID.
func (mr *MockSubscriptionRepositoryMockRecorder) GetSubscriptionBySubID(ctx, subID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionBySubID", reflect.TypeOf((*MockSubscriptionRepository)(nil).GetSubscriptionBySubID), ctx, subID)
}

// GetSubscriptionByUserID mocks base method.
func (m *MockSubscriptionRepository) GetSubscriptionByUserID(ctx context.Context, userID string) (*domain.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionByUserID", ctx, userID)
	ret0, _ := ret[0].(*domain.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionByUserID indicates an expected call of GetSubscriptionByUserID.
func (mr *MockSubscriptionRepositoryMockRecorder) GetSubscriptionByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionByUserID", reflect.TypeOf((*MockSubscriptionRepository)(nil).GetSubscriptionByUserID), ctx, userID)
}

// UpdateSubscription mocks base method.
func (m *MockSubscriptionRepository) UpdateSubscription(ctx context.Context, subscription *domain.Subscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubscription", ctx, subscription)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSubscription indicates an expected call of UpdateSubscription.
func (mr *MockSubscriptionRepositoryMockRecorder) UpdateSubscription(ctx, subscription any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubscription", reflect.TypeOf((*MockSubscriptionRepository)(nil).UpdateSubscription), ctx, subscription)
}
